/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany;

import com.mycompany.daos.ViagemDAO;
import com.mycompany.models.Lugar;
import com.mycompany.models.Pessoa;
import com.mycompany.models.Veiculo;
import com.mycompany.models.Viagem;

/**
 *
 * @author larissa
 */
public class FormViagem extends javax.swing.JFrame {
    private Viagem viagem;
    private Pessoa P;
    private Lugar origem;
    private Lugar destino;
    private Veiculo V;
    private ViagemDAO viagemDAO;
    /**
     * Creates new form FormViagem
     */
    public FormViagem() {
        initComponents();
        viagem = new Viagem();
        P = new Pessoa();
        origem = new Lugar();
        destino = new Lugar();
        V = new Veiculo();
        viagemDAO = new ViagemDAO();
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pessoaJL = new javax.swing.JLabel();
        origemJL = new javax.swing.JLabel();
        destinoJL = new javax.swing.JLabel();
        modeloVeiculoJL = new javax.swing.JLabel();
        partidaJL = new javax.swing.JLabel();
        chegadaJL = new javax.swing.JLabel();
        pessoaTF = new javax.swing.JTextField();
        origemTF = new javax.swing.JTextField();
        destinoTF = new javax.swing.JTextField();
        modeloVeiculoTF = new javax.swing.JTextField();
        partidaTF = new javax.swing.JTextField();
        chegadaTF = new javax.swing.JTextField();
        salvarBT = new javax.swing.JButton();
        exibirBT = new javax.swing.JButton();
        placaVeiculoJL = new javax.swing.JLabel();
        placaVeiculoTF = new javax.swing.JTextField();
        retornoPessoaJL = new javax.swing.JLabel();
        retornoOrigemJL = new javax.swing.JLabel();
        retornoDestinoJL = new javax.swing.JLabel();
        retornoModeloJL = new javax.swing.JLabel();
        retornoPlacaJL = new javax.swing.JLabel();
        retornoPartidaJL = new javax.swing.JLabel();
        retornoChegadaJL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Viagem");

        pessoaJL.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        pessoaJL.setText("Pessoa: ");

        origemJL.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        origemJL.setText("Origem:");

        destinoJL.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        destinoJL.setText("Destino:");

        modeloVeiculoJL.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        modeloVeiculoJL.setText("Modelo do veículo:");

        partidaJL.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        partidaJL.setText("Partida");

        chegadaJL.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        chegadaJL.setText("Chegada:");

        salvarBT.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        salvarBT.setText("Salvar");
        salvarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBTActionPerformed(evt);
            }
        });

        exibirBT.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        exibirBT.setText("Exibir");
        exibirBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirBTActionPerformed(evt);
            }
        });

        placaVeiculoJL.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        placaVeiculoJL.setText("Placa do veículo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(destinoJL)
                            .addComponent(modeloVeiculoJL)
                            .addComponent(placaVeiculoJL)
                            .addComponent(partidaJL)
                            .addComponent(chegadaJL))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(partidaTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(destinoTF)
                            .addComponent(modeloVeiculoTF)
                            .addComponent(placaVeiculoTF)
                            .addComponent(chegadaTF)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(origemJL)
                            .addComponent(pessoaJL))
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pessoaTF)
                            .addComponent(origemTF))))
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(salvarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(exibirBT, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(retornoChegadaJL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(retornoPartidaJL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(retornoPlacaJL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(retornoModeloJL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(retornoDestinoJL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(retornoOrigemJL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(retornoPessoaJL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(287, 287, 287))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pessoaJL)
                    .addComponent(pessoaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(origemJL))
                    .addComponent(origemTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinoJL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeloVeiculoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeloVeiculoJL))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(placaVeiculoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(placaVeiculoJL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partidaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partidaJL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chegadaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chegadaJL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(retornoPessoaJL)
                .addGap(18, 18, 18)
                .addComponent(retornoOrigemJL)
                .addGap(18, 18, 18)
                .addComponent(retornoDestinoJL)
                .addGap(18, 18, 18)
                .addComponent(retornoModeloJL)
                .addGap(18, 18, 18)
                .addComponent(retornoPlacaJL)
                .addGap(18, 18, 18)
                .addComponent(retornoPartidaJL)
                .addGap(18, 18, 18)
                .addComponent(retornoChegadaJL)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exibirBT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salvarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBTActionPerformed
        // TODO add your handling code here:
        P.setNome(pessoaTF.getText());
        origem.setNome(origemTF.getText());
        destino.setNome(destinoTF.getText());
        V.setModelo(modeloVeiculoTF.getText());
        V.setPlaca(placaVeiculoTF.getText());
        String partida = partidaTF.getText();
        String chegada = chegadaTF.getText();

        viagem.setNome_pessoa(pessoaTF.getText());
        viagem.setCpf_pessoa("123456");
        viagem.setOrigem(origemTF.getText());
        viagem.setDestino(destinoTF.getText());
        viagem.setModelo_veiculo(modeloVeiculoTF.getText());
        viagem.setPlaca_veiculo(placaVeiculoTF.getText());
        viagem.setDataPartida(partida);
        viagem.setDataChegada(chegada);
        
        viagemDAO.save(viagem);
        
        pessoaTF.setText("");
        origemTF.setText("");
        destinoTF.setText("");
        modeloVeiculoTF.setText("");
        placaVeiculoTF.setText("");
        partidaTF.setText("");
        chegadaTF.setText("");
        retornoModeloJL.setText("Dados armazenados");
    }//GEN-LAST:event_salvarBTActionPerformed

    private void exibirBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirBTActionPerformed
        // TODO add your handling code here:
        
        Viagem v = viagemDAO.getLastViagem();
        
        String pessoa = v.getNome_pessoa();
        String origem = v.getOrigem();
        String destino = v.getDestino();
        String modelo = v.getModelo_veiculo();
        String placa = v.getPlaca_veiculo();
        String partida = v.getDataPartida().toString();
        String chegada = v.getDataChegada().toString();
        retornoPessoaJL.setText("Pessoa: " + pessoa);
        retornoOrigemJL.setText("Origem: " + origem);
        retornoDestinoJL.setText("Destino: " + destino);
        retornoModeloJL.setText("Modelo do veículo: " + modelo);
        retornoPlacaJL.setText("Placa do veículo: " + placa);
        retornoPartidaJL.setText("Partida: " + partida);
        retornoChegadaJL.setText("Chegada: " + chegada);
    }//GEN-LAST:event_exibirBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormViagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormViagem FormViagem = new FormViagem();
                FormViagem.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chegadaJL;
    private javax.swing.JTextField chegadaTF;
    private javax.swing.JLabel destinoJL;
    private javax.swing.JTextField destinoTF;
    private javax.swing.JButton exibirBT;
    private javax.swing.JLabel modeloVeiculoJL;
    private javax.swing.JTextField modeloVeiculoTF;
    private javax.swing.JLabel origemJL;
    private javax.swing.JTextField origemTF;
    private javax.swing.JLabel partidaJL;
    private javax.swing.JTextField partidaTF;
    private javax.swing.JLabel pessoaJL;
    private javax.swing.JTextField pessoaTF;
    private javax.swing.JLabel placaVeiculoJL;
    private javax.swing.JTextField placaVeiculoTF;
    private javax.swing.JLabel retornoChegadaJL;
    private javax.swing.JLabel retornoDestinoJL;
    private javax.swing.JLabel retornoModeloJL;
    private javax.swing.JLabel retornoOrigemJL;
    private javax.swing.JLabel retornoPartidaJL;
    private javax.swing.JLabel retornoPessoaJL;
    private javax.swing.JLabel retornoPlacaJL;
    private javax.swing.JButton salvarBT;
    // End of variables declaration//GEN-END:variables
}
