/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany;

/**
 *
 * @author larissa
 */
public class FormMain extends javax.swing.JFrame {

    private FormPessoa FormPessoa;
    private FormViagem FormViagem;
    private FormLugar FormLugar;
    private FormVeiculo FormVeiculo;

    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
        FormPessoa = new FormPessoa();
        FormViagem = new FormViagem();
        FormLugar = new FormLugar();
        FormVeiculo = new FormVeiculo();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pessoaBT = new javax.swing.JButton();
        lugarBT = new javax.swing.JButton();
        veiculoBT = new javax.swing.JButton();
        viagemBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pessoaBT.setText("Pessoa");
        pessoaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoaBTActionPerformed(evt);
            }
        });

        lugarBT.setText("Lugar");
        lugarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugarBTActionPerformed(evt);
            }
        });

        veiculoBT.setText("Veículo");
        veiculoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoBTActionPerformed(evt);
            }
        });

        viagemBT.setText("Viagem");
        viagemBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viagemBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(432, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pessoaBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lugarBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(veiculoBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viagemBT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(446, 446, 446))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(pessoaBT)
                .addGap(67, 67, 67)
                .addComponent(lugarBT)
                .addGap(66, 66, 66)
                .addComponent(veiculoBT)
                .addGap(71, 71, 71)
                .addComponent(viagemBT)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viagemBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viagemBTActionPerformed
        // TODO add your handling code here:
        FormViagem.setVisible(true);
    }//GEN-LAST:event_viagemBTActionPerformed

    private void veiculoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoBTActionPerformed
        // TODO add your handling code here:
        FormVeiculo.setVisible(true);
    }//GEN-LAST:event_veiculoBTActionPerformed

    private void lugarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugarBTActionPerformed
        // TODO add your handling code here:
        FormLugar.setVisible(true);
    }//GEN-LAST:event_lugarBTActionPerformed

    private void pessoaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoaBTActionPerformed
        // TODO add your handling code here:
        FormPessoa.setVisible(true);
    }//GEN-LAST:event_pessoaBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton lugarBT;
    private javax.swing.JButton pessoaBT;
    private javax.swing.JButton veiculoBT;
    private javax.swing.JButton viagemBT;
    // End of variables declaration//GEN-END:variables
}
