/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany;

import com.mycompany.daos.PessoaDAO;
import com.mycompany.models.Pessoa;

/**
 *
 * @author larissa
 */
public class FormPessoa extends javax.swing.JFrame {
    
    private Pessoa P;
    private PessoaDAO pessoaDAO;
    /**
     * Creates new form FormPessoa
     */
    public FormPessoa() {
        initComponents();
        P= new Pessoa();
        pessoaDAO = new PessoaDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeJL = new javax.swing.JLabel();
        cpfJL = new javax.swing.JLabel();
        idadeJL = new javax.swing.JLabel();
        nomeTF = new javax.swing.JTextField();
        cpfTF = new javax.swing.JTextField();
        idadeTF = new javax.swing.JTextField();
        salvarBT = new javax.swing.JButton();
        exibirBT = new javax.swing.JButton();
        retornoNomeJL = new javax.swing.JLabel();
        retornoCpfJL = new javax.swing.JLabel();
        retornoIdadeJL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pessoa");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        nomeJL.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        nomeJL.setText("Nome:");

        cpfJL.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        cpfJL.setText("CPF:");

        idadeJL.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        idadeJL.setText("Idade: ");

        salvarBT.setText("Salvar");
        salvarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBTActionPerformed(evt);
            }
        });

        exibirBT.setText("Exibir");
        exibirBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirBTActionPerformed(evt);
            }
        });

        retornoNomeJL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        retornoCpfJL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        retornoIdadeJL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeJL)
                        .addGap(18, 18, 18)
                        .addComponent(nomeTF))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idadeJL)
                            .addComponent(cpfJL))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(retornoIdadeJL, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(retornoCpfJL, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cpfTF)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(salvarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(286, 286, 286)
                                        .addComponent(exibirBT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(retornoNomeJL, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(idadeTF))))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeJL)
                    .addComponent(nomeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfJL)
                    .addComponent(cpfTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idadeJL)
                    .addComponent(idadeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(retornoNomeJL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(retornoCpfJL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(retornoIdadeJL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exibirBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBTActionPerformed
        // TODO add your handling code here:
        P.setNome(nomeTF.getText());
        P.setCpf(cpfTF.getText());
        P.setIdade(Integer.parseInt(idadeTF.getText()));
        
        pessoaDAO.save(P);
        
        idadeTF.setText("");
        cpfTF.setText("");
        nomeTF.setText("");
        retornoCpfJL.setText("Dados armazenados");
    }//GEN-LAST:event_salvarBTActionPerformed

    private void exibirBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirBTActionPerformed
        // TODO add your handling code here:
        
        Pessoa pessoa = pessoaDAO.getLastPessoa();
        
        String nome = pessoa.getNome();
        String cpf = pessoa.getCpf();
        long idade = pessoa.getIdade();
        retornoNomeJL.setText("Nome: " + nome);
        retornoCpfJL.setText("CPF: " + cpf);
        retornoIdadeJL.setText("Idade: " + idade);
    }//GEN-LAST:event_exibirBTActionPerformed

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        setDefaultCloseOperation(FormPessoa.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cpfJL;
    private javax.swing.JTextField cpfTF;
    private javax.swing.JButton exibirBT;
    private javax.swing.JLabel idadeJL;
    private javax.swing.JTextField idadeTF;
    private javax.swing.JLabel nomeJL;
    private javax.swing.JTextField nomeTF;
    private javax.swing.JLabel retornoCpfJL;
    private javax.swing.JLabel retornoIdadeJL;
    private javax.swing.JLabel retornoNomeJL;
    private javax.swing.JButton salvarBT;
    // End of variables declaration//GEN-END:variables
}
